version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mongo:
      image: mongo
      container_name: mongo_container_productividad
      restart: always      
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: productividad
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: productividad
      ME_CONFIG_MONGODB_URL: mongodb://root:productividad@mongo:27017/
  Tomcat:
      image: tomcat
      container_name: tomcat_container
      volumes:
        - ../deployment/build:/usr/local/tomcat/webapps/build
      ports:
        - 8082:8080
      depends_on:
        - mongo
networks:
  productividad-and-mongo-network: